;;; packages.el --- chous-org Layer packages File for Spacemacs
;;
;; Copyright (c) 2012-2014 Sylvain Benner
;; Copyright (c) 2014-2015 Sylvain Benner & Contributors
;;
;; Author: Sylvain Benner <sylvain.benner@gmail.com>
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

;; List of all packages to install and/or initialize. Built-in packages
;; which require an initialization must be listed explicitly in the list.
(defconst chous-org-packages
    '(
      ;; package names go here
      (org location: org)
      (org-alert) ; location: elpa)
      (org-beautify-theme) ; location: elpa)
      (org-doing location: elpa)
      (ob-browser location: elpa)
      (ob-mongo location: elpa)
      (ob-restclient location: elpa)
      (ob-sml location: elpa)
;      (ob-shell)
      (ob-translate location: elpa)
      (org-ac location: elpa)
;      (org-agenda-properties location: elpa)
      (org-attach-screenshot location: elpa)
      (org-autolist location: elpa)
      (org-context location: elpa)
      (org-dashboard location: elpa)
      (org-dotemacs location: elpa)
      (org-drill-table location: elpa)
      (org-ehtml location: elpa)
      (org-elisp-help) ; location: elpa)
      ;;(org-eww location: elpa)
      (org-fstree location: elpa)
      (org-gcal location: elpa)
      (org-grep location: elpa)
      (org-if location: elpa)
      (org-jekyll location: elpa)
      (org-jira location: elpa)
      (org-journal location: elpa)
      (org-link-travis location: elpa)
      (org-linkany location: elpa)
      (org-mobile-sync location: elpa)
      (org-multiple-keymap location: elpa)
      (org-pdfview location: elpa)
      (org-protocol-jekyll location: elpa)
      (org-readme location: elpa)
      (org-ref location: elpa)
      ;;(org-table location: elpa)
      (org-time-budgets location: elpa)
      (org-transform-tree-table location: elpa)
      (org-tree-slide location: elpa)
;      (org-trello location: elpa)
      (org-vcard location: elpa)
      (org-wc location: elpa)
      (orglue location: elpa)
      (orgtbl-aggregate location: elpa)
      (orgtbl-ascii-plot location: elpa)
      (orgtbl-join location: elpa)
      (orgtbl-show-header location: elpa)
      (bog location: elpa)
      (code-library location: elpa)
      (epresent location: elpa)
      (gnorb location: elpa)
      (helm-orgcard location: elpa)
      (hideshow-org location: elpa)
      (literate-starter-kit location: elpa)
      ))

;; List of packages to exclude.
(defconst chous-org-excluded-packages '())

;; For each package, define a function chous-org/init-<package-name>
;;
;; (defun chous-org/init-my-package ()
;;   "Initialize my package"
;;   )
;;
(defun chous-org/init-org ()
  (use-package org)
  )
(defun chous-org/init-org-doing ()
  (use-package org-doing)
  )
(defun chous-org/init-ob-browser ()
  (use-package ob-browser)
  )
(defun chous-org/init-ob-mongo ()
  (use-package ob-mongo)
  )
(defun chous-org/init-ob-restclient ()
  (use-package ob-restclient)
  )
(defun chous-org/init-ob-sml ()
  (use-package ob-sml)
  )
(defun chous-org/init-ob-translate ()
  (use-package ob-translate)
  )
(defun chous-org/init-org-ac ()
  (use-package org-ac)
  )
(defun chous-org/init-org-agenda-properties ()
  (use-package org-agenda-properties)
  )
(defun chous-org/init-org-attach-screenshot ()
  (use-package org-attach-screenshot)
  )
(defun chous-org/init-org-autolist ()
  (use-package org-autolist)
  )
(defun chous-org/init-org-context ()
  (use-package org-context)
  )
(defun chous-org/init-org-dashboard ()
  (use-package org-dashboard)
  )
(defun chous-org/init-org-dotemacs ()
  (use-package org-dotemacs)
  )
(defun chous-org/init-org-drill-table ()
  (use-package org-drill-table)
  )
(defun chous-org/init-org-ehtml ()
  (use-package org-ehtml)
  )
(defun chous-org/init-org-elisp-help ()
  (use-package org-elisp-help)
  )
(defun chous-org/init-org-eww ()
  (use-package org-eww)
  )
(defun chous-org/init-org-fstree ()
  (use-package org-fstree)
  )
(defun chous-org/init-org-gcal ()
  (use-package org-gcal)
  )
(defun chous-org/init-org-grep ()
  (use-package org-grep)
  )
(defun chous-org/init-org-if ()
  (use-package org-if)
  )
(defun chous-org/init-org-jekyll ()
  (use-package org-jekyll)
  )
(defun chous-org/init-org-jira ()
  (use-package org-jira)
  )
(defun chous-org/init-org-journal ()
  (use-package org-journal)
  )
(defun chous-org/init-org-link-travis ()
  (use-package org-link-travis)
  )
(defun chous-org/init-org-linkany ()
  (use-package org-linkany)
  )
(defun chous-org/init-org-mobile-sync ()
  (use-package org-mobile-sync)
  )
(defun chous-org/init-org-multiple-keymap ()
  (use-package org-multiple-keymap)
  )
(defun chous-org/init-org-pdfview ()
  (use-package org-pdfview)
  )
(defun chous-org/init-org-protocol-jekyll ()
  (use-package org-protocol-jekyll)
  )
(defun chous-org/init-org-readme ()
  (use-package org-readme)
  )
(defun chous-org/init-org-ref ()
  (use-package org-ref)
  )
(defun chous-org/init-org-table ()
  (use-package org-table)
  )
(defun chous-org/init-org-time-budgets ()
  (use-package org-time-budgets)
  )
(defun chous-org/init-org-transform-tree-table ()
  (use-package org-transform-tree-table)
  )
(defun chous-org/init-org-tree-slide ()
  (use-package org-tree-slide)
  )
(defun chous-org/init-org-trello ()
  (use-package org-trello)
  )
(defun chous-org/init-org-vcard ()
  (use-package org-vcard)
  )
(defun chous-org/init-org-wc ()
  (use-package org-wc)
  )
(defun chous-org/init-orglue ()
  (use-package orglue)
  )
(defun chous-org/init-orgtbl-aggregate () 
  (use-package orgtbl-aggregate)
  )
(defun chous-org/init-orgtbl-ascii-plot ()
  (use-package orgtbl-ascii-plot)
  )
(defun chous-org/init-orgtbl-join ()
  (use-package orgtbl-join)
  )
(defun chous-org/init-orgtbl-show-header ()
  (use-package orgtbl-show-header)
  )
(defun chous-org/init-bog ()
  (use-package bog)
  )
(defun chous-org/init-code-library ()
  (use-package code-library)
  )
(defun chous-org/init-epresent ()
  (use-package epresent)
  )
(defun chous-org/init-gnorb ()
  (use-package gnorb)
  )
(defun chous-org/init-helm-orgcard ()
  (use-package helm-orgcard)
  )
(defun chous-org/init-hideshow-org ()
  (use-package hideshow-org)
  )
(defun chous-org/init-literate-starter-kit ()
  (use-package literate-starter-kit)
  )
(defun chous-org/init-ob-browser ()
  (use-package ob-browser)
  )
(defun chous-org/init-org-alert ()
  (use-package org-alert)
  )
(defun chous-org/init-org-beautify-theme ()
  (use-package org-beautify-theme)
  )
(defun chous-org/init-ob-shell ()
  (use-package ob-shell)
  )
;; Often the body of an initialize function uses `use-package'
;; For more info on `use-package', see readme:
;; https://github.com/jwiegley/use-package
