;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
;; (setq user-full-name "John Doe"
;;      user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
;; (setq doom-font (font-spec :family "monospace" :size 12 :weight 'semi-light)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
;; (setq doom-theme 'doom-one)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
;; (setq org-directory "~/org/")

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
;; (setq display-line-numbers-type t)

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;(if (s-starts-with-p "26" emacs-version)
(if (string= "26.3" emacs-version)
    (defvar eshell-modules-list
      '(eshell-alias
        eshell-banner
        eshell-basic
        eshell-cmpl
        eshell-dirs
        eshell-glob
        eshell-hist
        eshell-ls
        eshell-pred
        eshell-prompt
        eshell-script
        eshell-term
        eshell-unix
       )
    )
)

;; Enables Nixos-installed packages to be loaded
(require 'package)
(setq package-enable-at-startup nil)
(package-initialize)

;;; config.el --- -*- lexical-binding: t -*-

(setq kill-whole-line t)

(setq user-full-name "Jose San Leandro"
      user-mail-address "github@acm-sl.org"
      calendar-location-name "Madrid, ES"
      calendar-latitude 40.357102
      calendar-longitude -3.90059
      calendar-christian-all-holidays-flag t
      calendar-date-style 'european)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type 'relative)

(setq auto-save-default t
      make-backup-files t)

(setq confirm-kill-emacs nil)

(let ((alternatives '("doom-emacs-color.png")))
   ;;((alternatives '("doom-emacs-color.png" "doom-emacs-bw-light.svg")))
  (setq fancy-splash-image
        (concat doom-private-dir "splash/"
                (nth (random (length alternatives)) alternatives))))

(setq doom-font (font-spec :family "Fira Code" :size 18)
      doom-variable-pitch-font (font-spec :family "ETBembo" :size 20)
      doom-unicode-font (font-spec :family "Symbola" :size 20)
      doom-big-font (font-spec :family "Inconsolata" :size 24)
)

(add-hook! 'org-mode-hook #'mixed-pitch-mode)
(setq mixed-pitch-variable-pitch-cursor nil)

(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t
  )
)

(setq my-themes
      '(doom-ayu-dark
        doom-dark+
        doom-dracula
        doom-gruvbox
        doom-henna
        doom-laserwave
        doom-miramare
        doom-nord-light
        doom-oceanic-next
        doom-rouge
        doom-shades-of-purple
        doom-snazzy
        doom-tomorrow-night
        doom-xcode
        doom-vibrant
        doom-acario-dark
        doom-acario-light
        doom-city-lights
        doom-challenger-deep
        doom-dark+
        doom-dracula
        doom-ephemeral
        doom-fairy-floss
        doom-flatwhite
        doom-gruvbox
        doom-gruvbox-light
        doom-henna
        doom-horizon
        doom-Iosvkem
        doom-laserwave
        doom-material
        doom-manegarm
        doom-miramare
        doom-molokai
        doom-monokai-classic
        doom-monokai-pro
        doom-moonlight
        doom-nord
        doom-nord-light
        doom-nova
        doom-oceanic-next
        doom-old-hope
        doom-opera
        doom-opera-light
        doom-outrun-electric
        doom-palenight
        doom-plain
        doom-peacock
        doom-rouge
        doom-snazzy
        doom-solarized-dark
        doom-solarized-light
        doom-sourcerer
        doom-spacegrey
        doom-tomorrow-day
        doom-tomorrow-night
        doom-wilmersdorf
        doom-zenburn))

(defun item-for-day-of-week (items)
  "Select an item from ITEMS based on the day of the week."
  (let* ((day-of-week (string-to-number (format-time-string "%u")))
         (items-per-week (/ (length items) 7))
         (index (+ (* items-per-week (- day-of-week 1)) (random (1+ (- items-per-week 1)))))
         (item (nth index items)))
    item))

(load-theme (item-for-day-of-week my-themes) t)

(map! "C-x b"   #'counsel-buffer-or-recentf
      "C-x C-b" #'counsel-switch-buffer)

(defun zz/counsel-buffer-or-recentf-candidates ()
  "Return candidates for `counsel-buffer-or-recentf'."
  (require 'recentf)
  (recentf-mode)
  (let ((buffers
         (delq nil
               (mapcar (lambda (b)
                         (when (buffer-file-name b)
                           (abbreviate-file-name (buffer-file-name b))))
                       (delq (current-buffer) (buffer-list))))))
    (append
     buffers
     (cl-remove-if (lambda (f) (member f buffers))
                   (counsel-recentf-candidates)))))

(advice-add #'counsel-buffer-or-recentf-candidates
            :override #'zz/counsel-buffer-or-recentf-candidates)

 (use-package! switch-buffer-functions
   :after recentf
   :preface
   (defun my-recentf-track-visited-file (_prev _curr)
     (and buffer-file-name
          (recentf-add-file buffer-file-name)))
   :init
   (add-hook 'switch-buffer-functions #'my-recentf-track-visited-file))

;;(map! "C-s" #'counsel-grep-or-swiper)
;;(map! "C-s" #'+default/search-buffer)

(use-package! visual-regexp-steroids
  :defer 3
  :config
  (require 'pcre2el)
  (setq vr/engine 'pcre2el)
  (map! "C-c s r" #'vr/replace)
  (map! "C-c s q" #'vr/query-replace))

(after! undo-fu
  (map! :map undo-fu-mode-map "C-?" #'undo-fu-only-redo))

(map! "M-g g" #'avy-goto-line)
(map! "M-g M-g" #'avy-goto-line)

(map! "M-g o" #'counsel-outline)

(after! smartparens
  (defun zz/goto-match-paren (arg)
    "Go to the matching paren/bracket, otherwise (or if ARG is not
    nil) insert %.  vi style of % jumping to matching brace."
    (interactive "p")
    (if (not (memq last-command '(set-mark
                                  cua-set-mark
                                  zz/goto-match-paren
                                  down-list
                                  up-list
                                  end-of-defun
                                  beginning-of-defun
                                  backward-sexp
                                  forward-sexp
                                  backward-up-list
                                  forward-paragraph
                                  backward-paragraph
                                  end-of-buffer
                                  beginning-of-buffer
                                  backward-word
                                  forward-word
                                  mwheel-scroll
                                  backward-word
                                  forward-word
                                  mouse-start-secondary
                                  mouse-yank-secondary
                                  mouse-secondary-save-then-kill
                                  move-end-of-line
                                  move-beginning-of-line
                                  backward-char
                                  forward-char
                                  scroll-up
                                  scroll-down
                                  scroll-left
                                  scroll-right
                                  mouse-set-point
                                  next-buffer
                                  previous-buffer
                                  previous-line
                                  next-line
                                  back-to-indentation
                                  doom/backward-to-bol-or-indent
                                  doom/forward-to-last-non-comment-or-eol
                                  )))
        (self-insert-command (or arg 1))
      (cond ((looking-at "\\s\(") (sp-forward-sexp) (backward-char 1))
            ((looking-at "\\s\)") (forward-char 1) (sp-backward-sexp))
            (t (self-insert-command (or arg 1))))))
  (map! "%" 'zz/goto-match-paren))

(setq +format-on-save-enabled-modes
  '(not emacs-lisp-mode  ; elisp's mechanisms are good enough
        sql-mode         ; sqlformat is currently broken
        tex-mode         ; latexindent is broken
        org-mode
        latex-mode))

(setq org-log-done "time"
      org-log-done-with-time 't)

(unless (boundp 'org-agenda-custom-commands)
  (setq org-agenda-custom-commands '()))

(setq org-agenda-custom-commands
      (append org-agenda-custom-commands
              '(("d" "Daily agenda and all TODOs"
                 ((agenda "" ((org-agenda-span 'day)))  ; review today's schedule
                  (todo "" ((org-agenda-overriding-header "Today's Tasks")
                            (org-agenda-skip-function
                             '(org-agenda-skip-entry-if 'notscheduled 'deadline 'todo '("TODO" "STRT"))))))))
             '(("c" "Completed Today" agenda ""
               ((org-agenda-overriding-header "Tasks completed today")
                (org-agenda-start-day "0d")
                (org-agenda-span 'day)
                (org-agenda-start-on-weekday nil)
                (org-agenda-start-with-log-mode t)
                (org-agenda-log-mode-items '(closed))
                (org-agenda-skip-function '(org-agenda-skip-entry-if 'notregexp "\\* DONE "))))))
)

(after! org
  (add-to-list 'org-file-apps
               '("\\.png\\'" . viewnior))
  (add-to-list 'org-file-apps
               '("\\.jpg\\'" . viewnior))
  (add-to-list 'org-file-apps
               '("\\.svg\\'" . viewnior))
)

(setq +format-on-save-enabled-modes
  '(not emacs-lisp-mode  ; elisp's mechanisms are good enough
        sql-mode         ; sqlformat is currently broken
        tex-mode         ; latexindent is broken
        org-mode
        latex-mode))

(after! org (setq org-directory "~/org/"))

(after! org (setq org-hide-emphasis-markers t))

(after! org (setq org-insert-heading-respect-content nil))

(after! org
  (setq org-log-done t)
  (setq org-log-into-drawer t))

(after! org
  (setq org-special-ctrl-a/e t)
  (setq org-special-ctrl-k t))

(after! org
  (setq org-use-speed-commands
        (lambda ()
          (and (looking-at org-outline-regexp)
               (looking-back "^\**")))))

(add-hook! org-mode (electric-indent-local-mode -1))

(setq org-agenda-include-diary t)

(add-to-list 'auto-mode-alist '("\\.dw\\'" . shell-script-mode))

(add-to-list 'auth-sources
             "~/.emacs.d/.local/etc/authinfo.gpg")
(add-to-list 'auth-sources
             "~/.authinfo.gpg")
(add-to-list 'auth-sources
             "~/.authinfo")
(add-to-list 'auth-sources
             "~/.authinfo.gpg")
(add-to-list 'auth-sources
             "~/.netrc")

(add-hook! org-mode :append
           #'visual-line-mode
           #'variable-pitch-mode)

(setq org-journal-file-format "%Y%m%d.org")

(setq org-journal-date-format "%A, %d %B %Y")
(setq org-journal-time-format "Reflexiones\n- \n** Qué recuerdo de ayer\n- \n** Qué me gustaría que pasara hoy\n- \n")

(setq org-agenda-files
      '("~/gtd/inbox.org" "~/org/events.ong" "~/org/blender.org" "~/org/a2sensor.org" "~/org/work.org" "~/org/notes.org" "~/org/journal.org" "~/org/todo.org" "~/org/org-notes.org"
      "~/org/habits.org"))

(defun zz/add-file-keybinding (key file &optional desc)
  (let ((key key)
        (file file)
        (desc desc))
    (map! :desc (or desc file)
          key
          (lambda () (interactive) (find-file file)))))

(zz/add-file-keybinding "C-c z e" "~/org/events.org" "events.org")
(zz/add-file-keybinding "C-c z w" "~/org/work.org" "work.org")
(zz/add-file-keybinding "C-c z d" "~/org/journal.org" "journal.org")
(zz/add-file-keybinding "C-c z t" "~/org/todo.org" "todo.org")
(zz/add-file-keybinding "C-c z n" "~/org/notes.org" "notes.org")
(zz/add-file-keybinding "C-c z b" "~/org/blender.org" "blender.org")
(zz/add-file-keybinding "C-c z a" "~/org/a2sensor.org" "a2sensor.org")

(use-package! org-protocol-jekyll)
(use-package! s)

(use-package org-protocol
  :demand
  :config
  (add-to-list 'org-capture-templates
               '("b" "Blender TODO" entry (file "~/org/blender.org")
                 "* TODO %? :blender:
:PROPERTIES:
  :Via:
  :Note:
  :END:
  :LOGBOOK:
  - State \"TODO\"       from \"\"           %U
  :END:"
                 :prepend t
                 :kill-buffer t
                 :created t        ; properties
                )
  )
  (add-to-list 'org-capture-templates
               '("e" "Event TODO" entry (file "~/org/events.org")
                 "* TODO %? :event:
:PROPERTIES:
  :Via:
  :Note:
  :END:
  :LOGBOOK:
  - State \"TODO\"       from \"\"           %U
  :END:"
                 :prepend t
                 :kill-buffer t
                 :created t        ; properties
                )
  )
  (add-to-list 'org-capture-templates
               '("h" "habits.org" entry (file "~/org/habits.org")
                 "* TODO %?
:PROPERTIES:
:STYLE: habit
:STATE: %^{State|TODO|MISSED|DONE}
:CREATED: %U
:END:"
                 :prepend t
                 :kill-buffer t
                 :created t        ; properties
                )
  )
  (add-to-list 'org-capture-templates
               '("w" "Work TODO" entry (file "~/org/work.org")
                 "* TODO %? :work:
:PROPERTIES:
  :Via:
  :Note:
  :END:
  :LOGBOOK:
  - State \"TODO\"       from \"\"           %U
  :END:"
                 :prepend t
                 :kill-buffer t
                 :created t        ; properties
                )
  )
  (add-to-list 'org-capture-templates
               '("T" "Personal TODO" entry (file "~/org/todo.org")
                 "* TODO %? :personal:
:PROPERTIES:
  :Via:
  :Note:
  :END:
  :LOGBOOK:
  - State \"TODO\"       from \"\"           %U
  :END:"
                 :prepend t
                 :kill-buffer t
                 :created t        ; properties
                )
  )
)

(use-package! org-protocol-capture-html
  :after org-protocol)

(use-package! deft)

(global-set-key (kbd "<f6>") 'org-capture)

(defun zz/org-download-paste-clipboard (&optional use-default-filename)
  (interactive "P")
  (require 'org-download)
  (let ((file
         (if (not use-default-filename)
             (read-string (format "Filename [%s]: "
                                  org-download-screenshot-basename)
                          nil nil org-download-screenshot-basename)
           nil)))
    (org-download-clipboard file)))

(after! org
  (setq org-download-method 'directory)
  (setq org-download-image-dir "images")
  (setq org-download-heading-lvl nil)
  (setq org-download-timestamp "%Y%m%d-%H%M%S_")
  (setq org-image-actual-width 300)
  (map! :map org-mode-map
        "C-c l a y" #'zz/org-download-paste-clipboard
        "C-M-y" #'zz/org-download-paste-clipboard))

(defun my-add-id-to-todo ()
  "Add ID property to TODOs."
  (when (and (string= (org-get-todo-state) "TODO")
             (not (org-entry-get (point) "ID")))
    (org-id-get-create)))
(after! org-id
  (setq org-id-link-to-org-use-id 'create-if-interactive)
  (add-hook 'org-insert-heading-hook 'my-add-id-to-todo)
)

(map! :after counsel :map org-mode-map
      "C-c l l h" #'counsel-org-link)

(after! counsel
  (setq counsel-outline-display-style 'title))

(after! org-agenda
  (setq org-agenda-prefix-format
        '((agenda . " %i %-12:c%?-12t% s")
          ;; Indent todo items by level to show nesting
          (todo . " %i %-12:c%l")
          (tags . " %i %-12:c")
          (search . " %i %-12:c")))
  (setq org-agenda-include-diary t))

;(use-package! holidays
;  :after org-agenda
;  :config
;  (require spanish-holidays)
;  (setq calendar-holidays
;        (append spanish-holidays)))

(use-package! org-super-agenda
  :commands (org-super-agenda-mode))
(after! org-agenda
  (org-super-agenda-mode))

(after! org-clock
  (setq org-clock-persist t)
  (org-clock-persistence-insinuate))

(defun my/org-skip-if-not-today ()
  "Skip org entries that are not scheduled for today."
  (let ((subtree-end (save-excursion (org-end-of-subtree t)))
        (scheduled (org-entry-get nil "SCHEDULED")))
    (if (and scheduled
             (not (string= (substring scheduled 0 10) (format-time-string "%Y-%m-%d"))))
        subtree-end
      nil)))

(add-to-list 'org-agenda-custom-commands
             '("A" "Tasks explicitly scheduled for today" agenda ""
               ((org-agenda-span 'day)
                (org-agenda-start-day "+0d")
                (org-agenda-skip-function 'my/org-skip-if-not-today)
                (org-deadline-warning-days 0))) t)

(setq org-gtd-update-ack "2.1.0")
(setq org-gtd-update-ack "3.0.0")
(use-package! org-gtd
  :after org
  :config
  ;; where org-gtd will put its files. This value is also the default one.
  (setq org-gtd-directory "~/org/gtd/")
  ;; package: https://github.com/Malabarba/org-agenda-property
  ;; this is so you can see who an item was delegated to in the agenda
  (setq org-agenda-property-list '("DELEGATED_TO"))
  ;; I think this makes the agenda easier to read
  (setq org-agenda-property-position 'next-line)
  ;; package: https://www.nongnu.org/org-edna-el/
  ;; org-edna is used to make sure that when a project task gets DONE,
  ;; the next TODO is automatically changed to NEXT.
  (setq org-edna-use-inheritance t)
  (org-edna-load)
  :bind
  (("C-c d c" . org-gtd-capture) ;; add item to inbox
   ("C-c d a" . org-agenda-list) ;; see what's on your plate today
   ("C-c d p" . org-gtd-process-inbox) ;; process entire inbox
   ("C-c d n" . org-gtd-show-all-next) ;; see all NEXT items
   ;; see projects that don't have a NEXT item
   ("C-c d s" . org-gtd-show-stuck-projects)
   ;; the keybinding to hit when you're done editing an item in the
   ;; processing phase
   ("C-c d f" . org-gtd-clarify-finalize)))

(after! (org org-gtd)
  (add-to-list 'org-capture-templates
               '("i" "GTD item with link to where you are in emacs now"
                 entry
                 (file (lambda () (org-gtd--path org-gtd-inbox-file-basename)))
                 "* %?\n%U\n\n  %i\n  %a"
                 :kill-buffer t
                )
  )
)

(defadvice! +zz/load-org-gtd-before-capture (&optional goto keys)
    :before #'org-capture
    (require 'org-capture)
    (require 'org-gtd))

(after! org-roam
  (setq org-roam-directory "~/org/roam"))

(after! org-roam
  (setq org-roam-db-location "~/org/roam/.db"))

(after! org-roam
  (setq org-roam-index-file "index.org"))

(after! org-roam
  (setq org-roam-db-update-method 'idle-timer)
  (setq org-roam-db-update-idle-seconds 2))

(after! org-roam
  (org-roam-db-autosync-mode))

(add-hook 'after-init-hook 'org-roam-mode)

(defun my/org-capture-roam-setup ()
  (let ((capture-file (and (bound-and-true-p org-capture-mode)
                           (plist-get (org-capture-get :org-roam) :new-file))))
    (if (or (and (buffer-file-name)
                 (string-prefix-p (expand-file-name org-roam-directory)
                                  (expand-file-name (buffer-file-name))))
            (and capture-file
                 (string-prefix-p (expand-file-name org-roam-directory)
                                  (expand-file-name capture-file))))
        (local-set-key (kbd "C-c C-l") 'orb-insert-link)
      (local-set-key (kbd "C-c C-l") 'org-insert-link))))

(add-hook 'org-mode-hook 'my/org-capture-roam-setup)

(after! org-roam
  (setq org-roam-tag-sources '(prop vanilla)))

(use-package org-roam-bibtex
  :after org-roam
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :config
  (require 'org-ref)) ; Ensure org-ref is recognized

(setq org-roam-capture-templates
      '(("d" "default" plain
         "%?"
         :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                            "#+TITLE: ${title}\n#+roam_tags: roam\n")
         :unnarrowed t)))

                                        ;(use-package! ox-awesomecv
                                        ;  :after org)
                                        ;(use-package! ox-moderncv
                                        ;  :after org)

(use-package! ox-leanpub
  :after org
  :config
    (require 'ox-leanpub-markdown)
    (org-leanpub-book-setup-menu-markdown))

(after! ox-hugo
  (setq org-hugo-use-code-for-kbd t))

(defun zz/org-if-str (str &optional desc)
  (when (org-string-nw-p str)
    (or (org-string-nw-p desc) str)))

(defun zz/org-macro-hsapi-code (module &optional func desc)
  (org-link-make-string
   (concat "https://www.hammerspoon.org/docs/"
           (concat module (zz/org-if-str func (concat "#" func))))
   (or (org-string-nw-p desc)
       (format "=%s="
               (concat module
                       (zz/org-if-str func (concat "." func)))))))

(defun zz/org-macro-keys-code-outer (str)
  (mapconcat (lambda (s)
               (concat "~" s "~"))
             (split-string str)
             (concat (string ?\u200B) "+" (string ?\u200B))))
(defun zz/org-macro-keys-code-inner (str)
  (concat "~" (mapconcat (lambda (s)
                           (concat s))
                         (split-string str)
                         (concat (string ?\u200B) "-" (string ?\u200B)))
          "~"))
(defun zz/org-macro-keys-code (str)
  (zz/org-macro-keys-code-inner str))

(defun zz/org-macro-luadoc-code (func &optional section desc)
  (org-link-make-string
   (concat "https://www.lua.org/manual/5.3/manual.html#"
           (zz/org-if-str func section))
   (zz/org-if-str func desc)))

(defun zz/org-macro-luafun-code (func &optional desc)
  (org-link-make-string
   (concat "https://www.lua.org/manual/5.3/manual.html#"
           (concat "pdf-" func))
   (zz/org-if-str (concat "=" func "()=") desc)))

(defun zz/org-reformat-buffer ()
  (interactive)
  (when (y-or-n-p "Really format current buffer? ")
    (let ((document (org-element-interpret-data (org-element-parse-buffer))))
      (erase-buffer)
      (insert document)
      (goto-char (point-min)))))

                                        ;(use-package org-pandoc-import)

(defun zz/org-current-headline-number ()
  "Get the numbering of the innermost headline which contains the
cursor. Returns nil if the cursor is above the first level-1
headline, or at the very end of the file. Does not count
headlines tagged with :noexport:"
  (require 'org-num)
  (let ((org-num--numbering nil)
        (original-point (point)))
    (save-mark-and-excursion
      (let ((new nil))
        (org-map-entries
         (lambda ()
           (when (org-at-heading-p)
             (let* ((level (nth 1 (org-heading-components)))
                    (numbering (org-num--current-numbering level nil)))
               (let* ((current-subtree (save-excursion (org-element-at-point)))
                      (point-in-subtree
                       (<= (org-element-property :begin current-subtree)
                           original-point
                           (1- (org-element-property :end current-subtree)))))
                 ;; Get numbering to current headline if the cursor is in it.
                 (when point-in-subtree (push numbering
                                              new))))))
         "-noexport")
        ;; New contains all the trees that contain the cursor (i.e. the
        ;; innermost and all its parents), so we only return the innermost one.
        ;; We reverse its order to make it more readable.
        (reverse (car new))))))

(defun zz/refresh-reveal-prez ()
  ;; Export the file
  (org-re-reveal-export-to-html)
  (let* ((slide-list (zz/org-current-headline-number))
         (slide-str (string-join (mapcar #'number-to-string slide-list) "-"))
         ;; Determine the filename to use
         (file (concat (file-name-directory (buffer-file-name))
                       (org-export-output-file-name ".html" nil)))
         ;; Final URL including the slide number
         (uri (concat "file://" file "#/slide-" slide-str))
         ;; Get the document title
         (title (cadar (org-collect-keywords '("TITLE"))))
         ;; Command to reload the browser and move to the correct slide
         (cmd (concat
"osascript -e \"tell application \\\"Brave\\\" to repeat with W in windows
set i to 0
repeat with T in (tabs in W)
set i to i + 1
if title of T is \\\"" title "\\\" then
  reload T
  delay 0.1
  set URL of T to \\\"" uri "\\\"
  set (active tab index of W) to i
end if
end repeat
end repeat\"")))
    ;; Short sleep seems necessary for the file changes to be noticed
    (sleep-for 0.2)
    (call-process-shell-command cmd)))

(use-package! org-ml
  :after org)

;;(setq server-socket-dir "~/.emacs.d/server")
;;(server-start)

(add-hook! org-mode :append
  (add-hook! after-save :append :local #'org-babel-tangle))

;; (defun zz/sp-enclose-next-sexp (num)
;;   (interactive "p")
;;   (insert-parentheses (or num 1)))

;; (after! smartparens
;;   (add-hook! (clojure-mode
;;               emacs-lisp-mode
;;               lisp-mode
;;               cider-repl-mode
;;               racket-mode
;;               racket-repl-mode) :append #'smartparens-strict-mode)
;;   (add-hook! smartparens-mode :append #'sp-use-paredit-bindings)
;;   (map! :map (smartparens-mode-map smartparens-strict-mode-map)
;;         "M-(" #'zz/sp-enclose-next-sexp))

(after! prog-mode
  (map! :map prog-mode-map "C-h C-f" #'find-function-at-point)
  (map! :map prog-mode-map
        :localleader
        :desc "Find function at point"
        "g p" #'find-function-at-point))

(use-package! cfengine
  :defer t
  :commands cfengine3-mode
  :mode ("\\.cf\\'" . cfengine3-mode))

;(use-package! graphviz-dot-mode)

(after! magit
  (setq zz/repolist
        "~/.elvish/package-data/elvish-themes/chain-summary-repos.json")
  (defadvice! +zz/load-magit-repositories ()
    :before #'magit-list-repositories
    (setq magit-repository-directories
          (seq-map (lambda (e) (cons e 0)) (json-read-file zz/repolist))))
  (setq magit-repolist-columns
        '(("Name" 25 magit-repolist-column-ident nil)
          ("Status" 7 magit-repolist-column-flag nil)
          ("B<U" 3 magit-repolist-column-unpulled-from-upstream
           ((:right-align t)
            (:help-echo "Upstream changes not in branch")))
          ("B>U" 3 magit-repolist-column-unpushed-to-upstream
           ((:right-align t)
            (:help-echo "Local changes not in upstream")))
          ("Path" 99 magit-repolist-column-path nil))))

(use-package! iedit
  :defer
  :config
  (set-face-background 'iedit-occurrence "Magenta")
  :bind
  ("C-;" . iedit-mode))

(defmacro zz/measure-time (&rest body)
  "Measure the time it takes to evaluate BODY."
  `(let ((time (current-time)))
     ,@body
     (float-time (time-since time))))

(setq vterm-shell "/usr/local/bin/elvish")

(use-package! unfill
  :defer t
  :bind
  ("M-q" . unfill-toggle)
  ("A-q" . unfill-paragraph))

(remove-hook 'after-save-hook #'+literate|recompile-maybe)
(after! company
  (set-company-backend! 'org-mode nil)
)

(use-package! xterm-color)

(setq-hook! 'LaTeX-mode-hook +spellcheck-immediately nil)

; hlissner
(use-package! doom-snippets
  :after yasnippet)
; AndreaCrotti
(use-package! yasnippet-snippets
  :after yasnippet)
(after! yasnippet
  (yas-global-mode 1)
)

(after! yasnippet
  (yas-global-mode 1)
  (setq yas-snippet-dirs (append yas-snippet-dirs '("~/.doom.d/my-snippets")))
)

(use-package! magithub
  :after magit
  :commands (magithub-clone
             magithub-completion-enable)
  ;; :ensure t
  :config
  (magithub-feature-autoinject t)
  (setq
   magithub-clone-default-directory "$HOME/Git/Github/"
   magithub-dir (concat doom-etc-dir "magithub/")
   magithub-preferred-remote-method 'clone_url))

(after! pdf-view
  ;; open pdfs scaled to fit page
  (setq-default pdf-view-display-size 'fit-width)
  ;; automatically annotate highlights
  (setq pdf-annot-activate-created-annotations t
        pdf-view-resize-factor 1.1)
   ;; faster motion
 (map!
   :map pdf-view-mode-map
   :n "g g"          #'pdf-view-first-page
   :n "G"            #'pdf-view-last-page
   :n "N"            #'pdf-view-next-page-command
   :n "E"            #'pdf-view-previous-page-command
   :n "e"            #'evil-collection-pdf-view-previous-line-or-previous-page
   :n "n"            #'evil-collection-pdf-view-next-line-or-next-page
   :localleader
   (:prefix "o"
    (:prefix "n"
     :desc "Insert" "i" 'org-noter-insert-note))))

(setq org-catch-invisible-edits 'show-and-error)

(use-package! org-mind-map
  :general
  (:keymaps 'org-mode-map
            :states 'normal
            "m e m" '(org-mind-map-write :wk "Export mind-map") ))

(use-package! org-drill
  :after org)

(after! org-re-reveal
  (use-package! org-re-reveal-ref) ; fixes org-ref
  (setq reveal-extras (concat doom-private-dir "revealExtras/"))
)

(setq org-hugo-auto-set-lastmod 't
      org-hugo-section "posts"
      org-hugo-suppress-lastmod-period 43200.0
      org-hugo-export-creator-string "Emacs 27 (Org mode 9.4 + ox-hugo + HaoZeke)"
)

(setq auto-mode-alist (append '(("\\.envrc$" . shell-script-mode))
                              auto-mode-alist))

(use-package! groovy-mode
  :mode "\\.groovy\\'")

(define-minor-mode unpackaged/org-export-html-with-useful-ids-mode
  "Attempt to export Org as HTML with useful link IDs.
Instead of random IDs like \"#orga1b2c3\", use heading titles,
made unique when necessary."
  :global t
  (if unpackaged/org-export-html-with-useful-ids-mode
      (advice-add #'org-export-get-reference :override #'unpackaged/org-export-get-reference)
    (advice-remove #'org-export-get-reference #'unpackaged/org-export-get-reference)))

(defun unpackaged/org-export-get-reference (datum info)
  "Like `org-export-get-reference', except uses heading titles instead of random numbers."
  (let ((cache (plist-get info :internal-references)))
    (or (car (rassq datum cache))
        (let* ((crossrefs (plist-get info :crossrefs))
               (cells (org-export-search-cells datum))
               ;; Preserve any pre-existing association between
               ;; a search cell and a reference, i.e., when some
               ;; previously published document referenced a location
               ;; within current file (see
               ;; `org-publish-resolve-external-link').
               ;;
               ;; However, there is no guarantee that search cells are
               ;; unique, e.g., there might be duplicate custom ID or
               ;; two headings with the same title in the file.
               ;;
               ;; As a consequence, before re-using any reference to
               ;; an element or object, we check that it doesn't refer
               ;; to a previous element or object.
               (new (or (cl-some
                         (lambda (cell)
                           (let ((stored (cdr (assoc cell crossrefs))))
                             (when stored
                               (let ((old (org-export-format-reference stored)))
                                 (and (not (assoc old cache)) stored)))))
                         cells)
                        (when (org-element-property :raw-value datum)
                          ;; Heading with a title
                          (unpackaged/org-export-new-title-reference datum cache))
                        ;; NOTE: This probably breaks some Org Export
                        ;; feature, but if it does what I need, fine.
                        (org-export-format-reference
                         (org-export-new-reference cache))))
               (reference-string new))
          ;; Cache contains both data already associated to
          ;; a reference and in-use internal references, so as to make
          ;; unique references.
          (dolist (cell cells) (push (cons cell new) cache))
          ;; Retain a direct association between reference string and
          ;; DATUM since (1) not every object or element can be given
          ;; a search cell (2) it permits quick lookup.
          (push (cons reference-string datum) cache)
          (plist-put info :internal-references cache)
          reference-string))))

(defun unpackaged/org-export-new-title-reference (datum cache)
  "Return new reference for DATUM that is unique in CACHE."
  (cl-macrolet ((inc-suffixf (place)
                             `(progn
                                (string-match (rx bos
                                                  (minimal-match (group (1+ anything)))
                                                  (optional "--" (group (1+ digit)))
                                                  eos)
                                              ,place)
                                ;; HACK: `s1' instead of a gensym.
                                (-let* (((s1 suffix) (list (match-string 1 ,place)
                                                           (match-string 2 ,place)))
                                        (suffix (if suffix
                                                    (string-to-number suffix)
                                                  0)))
                                  (setf ,place (format "%s--%s" s1 (cl-incf suffix)))))))
    (let* ((title (org-element-property :raw-value datum))
           (ref (url-hexify-string (substring-no-properties title)))
           (parent (org-element-property :parent datum)))
      (while (--any (equal ref (car it))
                    cache)
        ;; Title not unique: make it so.
        (if parent
            ;; Append ancestor title.
            (setf title (concat (org-element-property :raw-value parent)
                                "--" title)
                  ref (url-hexify-string (substring-no-properties title))
                  parent (org-element-property :parent parent))
          ;; No more ancestors: add and increment a number.
          (inc-suffixf ref)))
      ref)))

;(setq org-latex-with-hyperref nil)

;; Compiler
(setq org-latex-pdf-process (list "latexmk -shell-escape -f -pdfxe %f"))

;; Configuration ; org-latex-packages-alist org-latex-minted-langs
; (setq org-latex-packages-alist '()); "minted" "xcolor" "tcolorbox"))
;(add-to-list 'org-latex-packages-alist '("minted" "xcolor"))
(setq org-latex-listings 'minted)
(setq org-latex-minted-options
  '(("bgcolor" "white") ("breaklines" "true") ("linenos" "true") ("style" "tango") ("breaksymbol" "")))
; (add-to-list 'org-latex-minted-langs '(bash "mylisting"))

(use-package! cdlatex
    :after (:any org-mode LaTeX-mode)
    :hook
    ((LaTeX-mode . turn-on-cdlatex)
     (org-mode . turn-on-org-cdlatex)))

(use-package! company-math
    :after (:any org-mode TeX-mode)
    :config
    (set-company-backend! 'org-mode 'company-math-symbols-latex)
    (set-company-backend! 'TeX-mode 'company-math-symbols-latex)
    (set-company-backend! 'org-mode 'company-latex-commands)
    (set-company-backend! 'TeX-mode 'company-latex-commands)
    (setq company-tooltip-align-annotations t)
    (setq company-math-allow-latex-symbols-in-faces t))

(use-package! math-symbol-lists
  :config
  (quail-define-package "math" "UTF-8" "Ω" t)
  (quail-define-rules ; add whatever extra rules you want to define here...
   ("\\from"    #X2190)
   ("\\to"      #X2192)
   ("\\lhd"     #X22B2)
   ("\\rhd"     #X22B3)
   ("\\unlhd"   #X22B4)
   ("\\unrhd"   #X22B5))
  (mapc (lambda (x)
          (if (cddr x)
              (quail-defrule (cadr x) (car (cddr x)))))
        (append math-symbol-list-basic math-symbol-list-extended math-symbol-list-subscripts math-symbol-list-superscripts)))

(defface endless/unimportant-latex-face
  '((t :height 0.7
       :inherit font-lock-comment-face))
  "Face used on less relevant math commands.")

(font-lock-add-keywords
 'latex-mode
 `((,(rx (or (and "\\" (or (any ",.!;")
                           (and (or "left" "right"
                                    "big" "Big")
                                symbol-end)))
             (any "_^")))
    0 'endless/unimportant-latex-face prepend))
 'end)

(setq org-src-preserve-indentation t
      org-edit-src-content-indentation 0)

(defun org-babel-execute:rst (body params)
  "Execute a block of rst code with org-babel.
This function is called by `org-babel-execute-src-block'."
  (let* ((result-params (split-string (or (cdr (assoc :results params)) "")))
       (in-file (org-babel-temp-file "rst-"))
       (cmdline (cdr (assoc :cmdline params)))
       (to (cdr (assoc :to params)))
       (template (cdr (assoc :template params)))
       (cmd (concat "pandoc"
                    " -t  org"
                    " -i " (org-babel-process-file-name in-file)
                    " -f rst "
                    " " cmdline)))
    (with-temp-file in-file (insert body))
    (message cmd)
    (shell-command-to-string cmd))) ;; Send to results

(defun org-babel-prep-session:rst (session params)
  "Return an error because rst does not support sessions."
  (error "rst does not support sessions"))

; Pdf
(defun haozeke/org-save-and-export-pdf ()
  (if (eq major-mode 'org-mode)
    (org-latex-export-to-pdf :async t)))

;; this function is used to append multiple elements to a list
(defun append-to-list (list-var elements)
  "Append ELEMENTS to the end of LIST-VAR. The return value is the new value of LIST-VAR."
  (unless (consp elements) (error "ELEMENTS must be a list"))
  (let ((list (symbol-value list-var)))
    (if list
        (setcdr (last list) elements)
      (set list-var elements)))
(symbol-value list-var))

(use-package! org-ref
  :ensure t
  :after org
  :init
  (setq reftex-default-bibliography '("~/org/bibliography/references.bib")
        org-ref-bibliography-notes "~/org/bibliography/notes.org"
        org-ref-default-bibliography '("~/org/bibliography/references.bib")
        org-ref-pdf-directory "~/org/bibliography/bibtex-pdfs/"
        bibtex-completion-bibliography "~/org/bibliography/references.bib"
        bibtex-completion-library-path "~/org/bibliography/bibtex-pdfs"
        bibtex-completion-notes-path "~/org/roam"
        bibtex-completion-pdf-open-function 'org-open-file
        bibtex-completion-pdf-field "file"
        org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f")
        org-ref-completion-library 'org-ref-ivy-cite
        org-ref-get-pdf-filename-function 'org-ref-get-pdf-filename-helm-bibtex
        org-ref-default-bibliography (list reftex-default-bibliography)
        org-ref-note-title-format "* TODO %y - %t\n :PROPERTIES:\n  :Custom_ID: %k\n  :NOTER_DOCUMENT: %F\n :ROAM_KEY: cite:%k\n  :AUTHOR: %9a\n  :JOURNAL: %j\n  :YEAR: %y\n  :VOLUME: %v\n  :PAGES: %p\n  :DOI: %D\n  :URL: %U\n :END:\n\n"
        org-ref-notes-directory "~/org/bibliography/"
        org-ref-notes-function 'orb-edit-notes
        bibtex-completion-notes-template-multiple-files
   (concat
    "#+TITLE: ${title}\n"
    "#+ROAM_KEY: cite:${=key=}\n"
    "#+ROAM_TAGS: ${keywords}\n"
    "* TODO Notes\n"
    ":PROPERTIES:\n"
    ":Custom_ID: ${=key=}\n"
    ":NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n"
    ":AUTHOR: ${author-abbrev}\n"
    ":JOURNAL: ${journaltitle}\n"
    ":DATE: ${date}\n"
    ":YEAR: ${year}\n"
    ":DOI: ${doi}\n"
    ":URL: ${url}\n"
    ":END:\n\n"
    )
    ))

 (use-package! org-roam-bibtex
  :after (org-roam)
  :hook (org-roam-mode . org-roam-bibtex-mode)
  :config
  (setq org-roam-bibtex-preformat-keywords
   '("=key=" "title" "url" "file" "author-or-editor" "keywords")
   org-roam-capture-templates
      '(("r" "related note" plain (function org-roam-capture--get-point)
         "* %?\n* Bibliographic Reference\n  - See main note: [[id:%^{Primary Note ID}][%^{Title of the Book}]]"
         :file-name "related-notes/${slug}"
         :unnarrowed t)
        ("R" "bibliography reference" plain "%?"
        :target
        (file+head "references/${citekey}.org" "#+title: ${title}\n")
        :unnarrowed t))))

(use-package! vertico
  :init
  (vertico-mode)
)

(use-package! vertico-directory
  :after vertico
  :bind (:map vertico-map
              ("RET" . vertico-directory-enter)
              ("DEL" . vertico-directory-delete-char)
              ("M-DEL" . vertico-directory-up)
              )
  )

(use-package! orderless
  :init
  (setq completion-styles '(orderless)
        completion-category-defaults nil)
  )

(use-package! embark
  :bind
  (("C-." . embark-act)         ;; pick some comfortable binding
   ("C-;" . embark-dwim)        ;; good alternative: "Do What I Mean"
   ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings`
  :init
  ;; Optionally replace the regular prefix help command with Embark's
  (setq prefix-help-command #'embark-prefix-help-command))

(use-package! consult
  :bind
  (("C-s" . consult-line)      ;; example: "search line" command
   ("M-y" . consult-yank-pop)) ;; example: "yank pop" with preview
  ;; Configure as needed...
  )

(use-package! embark-consult
  :after (embark consult))

(use-package! oc
  :after org
  :ensure nil
  :config
  (setq org-cite-global-bibliography '("~/org/bibliography/references.bib")
        org-cite-insert-processor 'vertico
        org-cite-follow-processor 'vertico
        org-cite-activate-processor 'vertico
  )
)

(use-package! org-noter
  :after (:any org pdf-view)
  :config
  (setq
   ;; The WM can handle splits
   org-noter-notes-window-location 'other-frame
   ;; Please stop opening frames
   org-noter-always-create-frame nil
   ;; I want to see the whole file
   org-noter-hide-other nil
   ;; Everything is relative to the rclone mega
;   org-noter-notes-search-path (list org_notes)
   )
  )

(set-popup-rule! "^CAPTURE-.*\\.org$" :size 0.5 :quit nil :select t :autosave t)

;; Fix some link issues
(defun transform-square-brackets-to-round-ones(string-to-transform)
  "Transforms [ into ( and ] into ), other chars left unchanged."
  (concat
   (mapcar #'(lambda (c) (if (equal c ?\[) ?\( (if (equal c ?\]) ?\) c))) string-to-transform))
  )

;; Actually start using templates
(after! (org org-capture)
  ;; Firefox
  (add-to-list 'org-capture-templates
               '("P" "Protocol -> inbox" entry
                 (file+headline +org-capture-notes-file "Inbox")
                 "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?"
                 :prepend t
                 :kill-buffer t
                 :created t        ; properties
                )
  )
  (add-to-list 'org-capture-templates
               '("L" "Protocol Link -> inbox" entry
                 (file+headline +org-capture-notes-file "Inbox")
                 "* %? [[%:link][%(transform-square-brackets-to-round-ones \"%:description\")]]\n"
                 :prepend t
                 :kill-buffer t
                 :created t        ; properties
                )
  )
)

(use-package! org-protocol-capture-html
  :after org-protocol
  :config
  (add-to-list 'org-capture-templates
               '("w"
                 "Web site"
                 entry
                 (file+headline +org-capture-notes-file "Website")  ; target
                 "* %a :website:\n\n%U %?\n\n%:initial"
                 :prepend t        ; properties
                 :empty-lines 1    ; properties
                 :created t        ; properties
               )
  )
)
(setq org-roam-ref-capture-templates
        '(("r" "ref" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "websites/${slug}"
           :head "#+SETUPFILE:./hugo_setup.org
#+ROAM_KEY: ${ref}
#+HUGO_SLUG: ${slug}
#+TITLE: ${title}")))

(use-package ein)

(use-package yankpad
  :defer 10
  :init
  (setq yankpad-file "~/org/yankpad.org")
  :config
  (bind-key "<f7>" 'yankpad-map)
  (bind-key "<f12>" 'yankpad-expand)
  ;; If you want to complete snippets using company-mode
  (add-to-list 'company-backends #'company-yankpad)
  ;; If you want to expand snippets with hippie-expand
  (add-to-list 'hippie-expand-try-functions-list #'yankpad-expand))

(use-package! volatile-highlights
  :config
  (volatile-highlights-mode t))

(use-package! poporg
      :bind (("C-c C-x /" . poporg-dwim)))

(use-package! elfeed
  :config
  (elfeed-load-opml "~/rss/podcasts.opml")
)
(after! elfeed
  (elfeed-add-feed "https://news.ycombinator.com/rss")
  (elfeed-add-feed "https://www.meneame.net/rss")
  (elfeed-add-feed "http://rss.slashdot.org/Slashdot/slashdotMain")
  (elfeed-add-feed "https://www.reddit.com/r/3dprinting/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/announcements/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/antiwork/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/arduino/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Art/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/AskReddit/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/askscience/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/aws/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/aww/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/binance/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/blog/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/books/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/clang/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/collapse/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/creepy/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/cryptocurrency/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/dataisbeautiful/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/datascience/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/docker/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/DIY/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Documentaries/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/domaindrivendesign/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/EarthPorn/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/ECE/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/emacs/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/engineering/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/eventsourcing/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/explainlikeimfive/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/fpga/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Fitness/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/food/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/funny/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Futurology/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/gadgets/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/gaming/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/GetMotivated/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/gifs/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/golang/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/grails/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/groovy/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/history/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/IAmA/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/ifttt/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/InterestingAsFuck/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/InternetIsBeautiful/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/java/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Jokes/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/keras/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/kubernetes/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/LifeProTips/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/listentothis/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/machinelearning/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/mildlyinteresting/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/movies/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Music/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/nextfuckinglevel/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/news/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Nixos/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/nosleep/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/nottheonion/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/oculusquest/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/OldSchoolCool/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/openai/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/personalfinance/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/philosophy/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/pics/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/podemos/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/python/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/science/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/raspberrypi/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/react/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/rust/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/serverless/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Showerthoughts/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/smalltalk/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/softwareengineering/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/space/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/sports/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/springboot/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/Stadia/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/television/.rss")
;  (elfeed-add-feed "https://www.reddit.com/r/tensorflow/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/tifu/.rss")
;  (elfeed-add-feed "https://www.reddit.com/r/til/.rss")
;  (elfeed-add-feed "https://www.reddit.com/r/todaywelearned/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/TwoXChromosomes/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/UpliftingNews/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/videos/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/vim/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/wallstreetbets/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/webassembly/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/webdev/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/whatsthatbook/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/worldnews/.rss")
  (elfeed-add-feed "https://www.reddit.com/r/WritingPrompts/.rss")
;  (elfeed-add-feed "https://www.reddit.com/r/YSK/.rss")
)

(use-package! alert
  :commands (alert)
  :init
  (setq alert-default-style
        (if (eq system-type 'darwin) 'osx-notifier 'libnotify))
)

(defun arrayify (start end quote)
  "Turn strings on newlines into a QUOTEd, comma-separated one-liner."
  (interactive "r\nMQuote: ")
  (let ((insertion
         (mapconcat
          (lambda (x) (format "%s%s%s" quote x quote))
          (split-string (buffer-substring start end)) ", ")))
    (delete-region start end)
    (insert insertion)))

(after! org
  (setq display-fill-column-indicator nil)
)

(use-package! js
  :config
  (setq js-indent-level 2)
)

(setq sh-basic-offset 2)

(after! format-all
  (set-formatter! 'shfmt
    '("shfmt"
      "-i" "2"
      ;; Mode selection copied from the default config
      ("-ln" "%s" (cl-case (and (boundp 'sh-shell) (symbol-value 'sh-shell))
                    (bash "bash") (mksh "mksh") (t "posix"))))
    :modes 'sh-mode))

;(setq format-all-show-errors 'never)

;(setq-hook! 'sh-mode-hook +format-with-lsp nix)

;(add-to-list '+format-on-save-enabled-modes 'sh-mode t)

;(add-hook! 'sh-mode-hook
;           (format-all-mode -1)
;           )

(use-package! blacken)

(use-package! lsp
  :init
  (setq lsp-pyls-plugins-pylint-enabled t)
  (setq lsp-pyls-plugins-autopep8-enabled nil)
  (setq lsp-pyls-plugins-yapf-enabled t)
  (setq lsp-pyls-plugins-pyflakes-enabled nil)
  (setq lsp-log-io t)
)

(setq-hook! 'yaml-mode-hook +format-with-lsp nil)

(use-package! lsp-java
  :ensure t
  :after lsp-mode
  :config
(add-hook 'java-mode-hook #'lsp))

(defun get-parent-directory (path)
  "Return the parent directory of PATH, or nil if there is no parent."
  (let ((parent (file-name-directory (directory-file-name (expand-file-name path)))))
    (if (and parent (not (string= parent path)))
        parent
      nil)))

(setq lsp-java-java-path (get-parent-directory (get-parent-directory (file-truename "/run/current-system/sw/bin/java"))))
(setq lsp-java-server-install-dir (file-truename "/run/current-system/sw/bin/jdtls"));(get-parent-directory (get-parent-directory (file-truename "/run/current-system/sw/bin/jdtls"))))

(use-package! dap-java
  :ensure t
  :after lsp-mode
  :config
(dap-auto-configure-mode)
(require 'dap-java)
)

(dap-register-debug-template "Java Attach 5005"
  (list :type "java"
        :request "attach"
        :hostName "localhost"
        :port 5005))
(dap-register-debug-template "Java Attach 4001"
  (list :type "java"
        :request "attach"
        :hostName "localhost"
        :port 4001))

(use-package! realgud
  :ensure t
)

(use-package! yasnippet
  :ensure t
  :config
  (yas-global-mode 1)
)

(setq debug-on-error t)

(global-unset-key (kbd "C-z"))

(global-set-key (kbd "C-z C-z") 'my-suspend-frame)

(defun my-suspend-frame ()
  "In a GUI environment, do nothing; otherwise `suspend-frame'."
  (interactive)
  (if (display-graphic-p)
      (message "suspend-frame disabled for graphical displays.")
    (suspend-frame)))

(use-package! solidity-mode
   :config
   (setq solidity-solium-path "~/io.builders/corporate-debt/syndicated-loan/contracts/node_modules/.bin/solium")
   (setq flycheck-solidity-solium-soliumrcfile "~/io.builders/corporate-debt/syndicated-loan/contracts/.soliumrc.json")
   (add-to-list 'flycheck-checkers 'solidity-checker)
   (add-to-list 'flycheck-checkers 'solium-checker)
   (setq flycheck-solidity-solc-addstd-contracts t)
   (setq solidity-flycheck-solc-checker-active t)
   (setq solidity-flycheck-solium-checker-active t)
   (add-hook 'solidity-mode-hook
          (lambda ()
            (add-to-list 'company-backends #'company-solidity)))
   (remove-hook! 'before-save-hook #'+format/buffer)
)

(use-package! solidity-flycheck)

(use-package! unicode-fonts :ensure t :config (unicode-fonts-setup))
(use-package! emojify
  :config
  (when (member "Segoe UI Emoji" (font-family-list))
    (set-fontset-font
     t 'symbol (font-spec :family "Segoe UI Emoji") nil 'prepend))
  (setq emojify-display-style 'unicode)
  (setq emojify-emoji-styles '(unicode))
  (bind-key* (kbd "C-c .") #'emojify-insert-emoji)) ; override binding in any mode
(defun my-emoji-fonts ()
  (set-fontset-font t 'symbol "Noto Color Emoji")
  (set-fontset-font t 'symbol "Symbola" nil 'append))
(if (daemonp)
(add-hook 'server-after-make-frame-hook #'my-emoji-fonts)
(my-emoji-fonts))

(defun delete-unicode-fonts-cache ()
  "Deletes the specified file upon Emacs exit."
  (let ((target-file "~/.emacs.d/.local/cache/pcache/unicode-fonts"))
    (when (file-exists-p target-file)
      (delete-file target-file))))
(add-hook 'kill-emacs-hook 'delete-unicode-fonts-cache)
(add-hook 'emacs-startup-hook 'delete-unicode-fonts-cache)

(setq exec-path (append exec-path '("~/bin")))

(use-package popwin
  :config
  (popwin-mode 1)
  (setq display-buffer-alist
      '(("/tmp/forensic/flake.nix"
         (display-buffer-reuse-window
          display-buffer-in-side-window)
         (side . right)
         (window-width . 0.25)
         (reusable-frames . nil)))))

;; accept completion from copilot and fallback to company
(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :bind (:map copilot-completion-map
              ("<tab>" . 'copilot-accept-completion)
              ("TAB" . 'copilot-accept-completion)
              ("C-TAB" . 'copilot-accept-completion-by-word)
              ("C-<tab>" . 'copilot-accept-completion-by-word))
  :config
  (with-eval-after-load 'warnings
    (add-to-list 'warning-suppress-types '(copilot)))
  )

(setq gnus-select-method
      '(nntp "news.eweka.nl" ; Replace with your news server address
             (nntp-port-number 583)
             (nntp-authinfo-file "~/.authinfo")))

(global-set-key (kbd "C-s") 'isearch-forward)
