;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; DO NOT EDIT THIS FILE DIRECTLY
;; This is a file generated from a literate programing source file located at
;; https://gitlab.com/zzamboni/dot-doom/-/blob/master/doom.org
;; You should make any changes there and regenerate it from Emacs org-mode
;; using org-babel-tangle (C-c C-v t)

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.

;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/raxod502/straight.el#the-recipe-format
;;(package! another-package
;;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;;(package! this-package
;;  :recipe (:host github :repo "username/repo"
;;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;;(package! builtin-package :recipe (:nonrecursive t))
;;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see raxod502/straight.el#279)
;;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;;(package! builtin-package :pin "1a2b3c4d5e")

;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;;(unpin! pinned-package)
;; ...or multiple packages
;;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;;(unpin! t)

(package! switch-buffer-functions)

(package! pcre2el)
(package! visual-regexp-steroids)

;(use-package! el-patch)

;(package! org-protocol)
(package! org-protocol-jekyll)
(package! s)
(package! deft)

(package! org-protocol-capture-html
  :recipe (:host github :repo "alphapapa/org-protocol-capture-html"
           :files ("org-protocol-capture-html.el")))

(package! org-download)

(package! screenshot
  :recipe (:host github :repo "tecosaur/screenshot"
           :files ("screenshot.el")))

(package! org-super-agenda)

(package! org-gtd)

(package! org-roam-bibtex)

(package! org-roam-ql)

(package! org-roam-timestamps)

(package! org-roam-ui)

(package! ox-leanpub)

                                        ;(package! org-pandoc-import
                                        ;  :recipe (:host github
                                        ;           :repo "tecosaur/org-pandoc-import"
                                        ;           :files ("*.el" "filters" "preprocessors")))

(package! org-ml)

(package! elvish-mode)
(package! ob-elvish)

(package! ob-cfengine3)

;(package! graphviz-dot-mode)

(package! package-lint)

(package! iedit)

(package! unfill)

(package! annotate)

(package! gift-mode)

(package! xterm-color)

; hlissner
(package! doom-snippets)
; AndreaCrotti
(package! yasnippet-snippets)

(package! org-drill)

(package! org-re-reveal-ref)

(package! org-ref)

(package! ivy)

(package! ivy-hydra)

(package! counsel)

(package! swiper)

(package! org-roam-bibtex)

(package! vertico)

(package! vertico-directory)

(package! orderless)

(package! embark)

(package! consult)

(package! oc)
(package! citeproc)

(package! ein)

(package! yankpad)

(package! volatile-highlights)

(package! poporg)

(package! elfeed)

(package! alert)

(package! outshine)

(package! js)

(package! blacken)

(package! solidity-mode)

(package! solidity-flycheck)

(package! unicode-fonts)
(package! emojify)

(package! popwin)

(package! copilot
  :recipe (:host github :repo "copilot-emacs/copilot.el" :files ("*.el" "dist")))

(package! gnus)
